### PR TITLE
package.json tweak for long paths in conda package

### PR DESCRIPTION
**Pull request by pjaggi1**

### CODE REVIEW

**Comment by hbcarlos** [comment]
Hi @pjaggi1! Thanks for opening the PR!

Do you mind explaining a little more in detail why you want to change that?

Maybe the command `jlpm run build:prod` does exactly what you need, see https://github.com/QuantStack/jupyterlab-js-logs/blob/9950cf30e438c79565939da4b825e5f9bccd45a5/package.json#L37

**Comment by pjaggi1** [comment]
> Hi @pjaggi1! Thanks for opening the PR!
> 
> Do you mind explaining a little more in detail why you want to change that?
> 
> Maybe the command `jlpm run build:prod` does exactly what you need, see
> 
> https://github.com/QuantStack/jupyterlab-js-logs/blob/9950cf30e438c79565939da4b825e5f9bccd45a5/package.json#L37

the way we package the files is by unpacking the conda package here-https://anaconda.org/conda-forge/jupyterlab-js-logs/0.2.4/download/noarch/jupyterlab-js-logs-0.2.4-pyhd8ed1ab_0.tar.bz2
I am not sure exactly how the conda package gets built, but it seems to be using the build (and not build:prod) argument.  Basically we would like for this to be rebuilt using build:prod (or by using the existing build with this change i'm proposing).

**Comment by pjaggi1** [comment]
> Hi @pjaggi1! Thanks for opening the PR!
> 
> Do you mind explaining a little more in detail why you want to change that?
> 
> Maybe the command `jlpm run build:prod` does exactly what you need, see
> 
> https://github.com/QuantStack/jupyterlab-js-logs/blob/9950cf30e438c79565939da4b825e5f9bccd45a5/package.json#L37

the current conda package has a couple of files like this:  vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-926fd9.aa45b7df615e3572a9b8.js.map
in it.  we would like for those not to be there-they are causing us (long path) issues during our installation process.
I am not sure how those packages are built, but it looks like use the build (and not build:prod) command during the creation of the package.  ultimately we would like a new package built-either changing the conda build to use build:prod or by keeping it as is and making this change.

**Comment by hbcarlos** [comment]
> would it be possible/better to change something here

No, I think the problem is that we are building the extension in dev mode when publishing the package.
I need to investigate a little bit more the issue, but what you are doing on this PR is on the right path, this way when using the [Jupyter Releaser](https://github.com/jupyter-server/jupyter_releaser), we will build in production.
If I recall correctly, the reason we are building in dev mode when publishing the package is that when I was adopting the Jupyter Releaser on this repo, I had some troubles building the extension with the release.

Let me investigate this a bit deeper.

**Comment by hbcarlos** [comment]
@pjaggi1 This issue should be solved now with v0.2.6.
You can already using installing from pypi, for the conda package will take a few hours to be published.

Thanks again for opening the PR!!

**Pull request closed without merging**
